//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facebook
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend
    {
        public int id_friends { get; set; }
        public string friends_name { get; set; }
    }
}
